import { StyleSheet, Dimensions } from 'react-native';
import colors from './Colors';

const windowHeight = Dimensions.get('window').height;
const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingTop: 0,
    flexDirection: 'row',
  },
  root: {
    backgroundColor: colors.active_color,
  },
  splashContainer: {
    backgroundColor: '#fff',
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
  },
  map: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    flex: 12,
  },
  welcome_logo_container: {
    flex: 1,
    alignItems: 'flex-end',
    justifyContent: 'center',
    flexDirection: 'row',
  },
  welcome_logo: {
    height: (windowHeight * 1) / 5,
    resizeMode: 'contain',
  },
  form_head: {
    flex: 0.1,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    backgroundColor: colors.active_color,
    paddingTop: 10,
    paddingBottom: 20,
  },
  title: {
    justifyContent: 'center',
    fontSize: 20,
    color: '#fff',
  },
  header: {
    flex: 1,
    justifyContent: 'center',
  },
  headerText: {
    textAlign: 'center',
    justifyContent: 'center',
    fontSize: 20,
    color: colors.primary,
  },
  body: {
    flex: 12,
    paddingTop: 25,
    paddingBottom: 100,
  },
  eventListRow: {
    padding: 10,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0,0,0,0.1)',
  },
  eventListRowTitle: {
    fontWeight: 'bold',
    color: 'rgba(25, 43, 62, 0.9)',
  },
  eventListRowDetails: {
    paddingTop: 5,
    color: 'rgba(25, 43, 62, 0.9)',
  },
  actionButtonContainer: {
    flex: 5,
    justifyContent: 'center',
  },
  mapMarker: {
    backgroundColor: 'rgba(25, 43, 62, 0.4)',
    height: 50,
    width: 50,
    borderRadius: 50 / 2,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(25, 43, 62, 0.9)',
    overflow: 'hidden',
  },
  mapMarkerPoint: {
    backgroundColor: 'rgba(25, 43, 62, 0.9)',
    height: 20,
    width: 20,
    borderRadius: 20 / 2,
    borderWidth: 1,
    borderColor: '#fff',
  },
  status: {
    flexDirection: 'row',
    marginTop: 20,
    marginBottom: 0,
    borderWidth: 0,
  },
  formRowText: {
    flexDirection: 'row',
    marginLeft: 30,
    marginRight: 30,
    marginTop: 20,
    marginBottom: 5,
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
  },
  formRow: {
    flex: 6,
    backgroundColor: '#fff',
    padding: 6,
    paddingBottom: 0,
    borderRadius: 4,
    borderWidth: 0.2,
    borderColor: '#607d8b',
    flexDirection: 'row',
    marginLeft: 20,
    marginRight: 30,
    marginTop: 5,
    marginBottom: 5,
  },
  descriptionContainer: {
    flexDirection: 'row',
    paddingLeft: 0,
    borderWidth: 0.2,
    borderTopRightRadius: 15,
    borderBottomRightRadius: 15,
    borderBottomLeftRadius: 15,
    paddingTop: 3,
    borderColor: 'rgba(0,0,0,0.04)',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
  },
  formContainer: {
    marginTop: 20,
  },
  actionsButtonsContainer: {
    flex: 1,
    flexDirection: 'row',
    position: 'absolute',
    bottom: 15,
    zIndex: 2000,
    right: 0,
    left: 0,
    paddingLeft: 20,
    paddingRight: 20,
  },
  description: {
    flex: 1,
    flexDirection: 'row',
    borderWidth: 0,
    borderTopRightRadius: 15,
    borderBottomRightRadius: 15,
    borderBottomLeftRadius: 15,
    alignItems: 'flex-end',
    justifyContent: 'flex-start',
    textAlignVertical: 'top',
    paddingLeft: 15,
    minHeight: 120,
  },
  formInputError: {
    flex: 6,
    padding: 6,
    paddingLeft: 6,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 0, 0, 1)',
    backgroundColor: 'rgba(0,0,0,0.04)',
    bottom: 0,
  },
  formButtons: {
    alignItems: 'center',
    marginTop: 15,
    flexDirection: 'row',
    justifyContent: 'center',
  },
  button: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 26,
    borderRadius: 15,
    paddingTop: 10,
    paddingBottom: 10,
    backgroundColor: colors.active_color,
  },
  buttonText: {
    color: '#fff',
    fontWeight: 'bold',
  },
  login: {
    alignItems: 'center',
    flexDirection: 'row',
    marginTop: 20,
    paddingTop: 10,
    paddingBottom: 10,
  },
  formBlock: {
    flexDirection: 'row',
    marginLeft: 20,
    marginRight: 30,
    marginTop: 20,
    marginBottom: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  btn: {
    backgroundColor: 'rgba(25, 43, 62, 0.9)',
    paddingTop: 10,
    paddingBottom: 10,
    paddingLeft: 20,
    paddingRight: 20,
    borderRadius: 30,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 20,
  },
  formHeader: {
    flexDirection: 'row',
    marginTop: 80,
    marginBottom: 20,
  },
  formInput: {
    flex: 5,
  },
  formLabel: {
    flex: 0.5,
    justifyContent: 'center',
    alignItems: 'center',
  },
  formLabelDescription: {
    flex: 0.5,
    justifyContent: 'flex-start',
    alignItems: 'center',
    marginTop: 10,
    borderTopLeftRadius: 15,
    borderBottomLeftRadius: 15,
  },
  labelText: {
    color: 'rgba(25, 43, 62, 0.9)',
  },
  formInputText: {
    backgroundColor: '#fff',
    padding: 10,
  },
  detailsCard: {
    margin: 30,
    padding: 20,
    backgroundColor: '#fff',
  },
  detailsCardTitle: {
    fontWeight: '600',
    color: '#222',
  },
  detailsCardBody: {
    fontSize: 16,
    marginTop: 10,
  },
  loaderContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  errorText: {
    flex: 1,
    textAlign: 'center',
    fontSize: 16,
  },
});

export { colors };
export default styles;
